name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rust:
    uses: raul2811/github-workflows/.github/workflows/rust-ci.yml@v1
    with:
      rust-version: "1.88.0"
      audit: true
      deny: true
